server:
  port: 3344

spring:
  application:
    name: cloud-config-center  # 注册进eureka Server 的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/isLiuHao/springcloud-config.git # github 仓库位置
          ## 搜索目录
          search-paths:
            - springcloud-config
          # 读取的分支
          label: master
# rabbitMq的相关配置
  rabbitmq:
    host: 192.168.0.102 #rabbitMq的安装ip地址
    port: 5672
    username: guest
    password: guest

# rabbitmq 的相关配置2 暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/


