server:
  port: 80
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.102:8848  #nacos配置地址
# http://192.168.0.102:8848/nacos 查看nacos注册中心
management:
  endpoints:
    web:
      exposure:
        include: '*'

# 自定义的一个属性，提供者服务地址
service-url:
  nacos-user-service: http://nacos-payment-provider