server:
  port: 80
spring:
  application:
    name: cloud-consumer-order
#consul注册中心地址
  cloud:
    consul:
      host: 172.18.56.100
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true
        heartbeat:
          enabled: true
