server:
  port: 8006
spring:
  application:
    name: consul-provider-payment
#consul注册中心地址
  cloud:
    consul:
      host: 172.18.56.100
      port: 8500
      discovery:    # 指定注册对外暴露的服务名称
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true