server:
  port: 84
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.102:8848  #nacos配置地址
      # http://192.168.0.102:8848/nacos 查看nacos注册中心
    sentinel:
      transport:
        # 配置 Sentinel Dashboard 的地址
        dashboard: 192.168.0.102:8858
        # 默认8719 ，如果端口被占用，端口号会自动 +1
        port: 8719
# 激活Sentinel对Feign的支持
feign:
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

# 自定义的一个属性，提供者服务地址
service-url:
  nacos-user-service: http://nacos-payment-provider